# This file will contain properties for prod environment
version: '3'
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - NODE_ENV=production
    command: node app.js

  # adding new service for mongo DB
  mongo:
  # we don't need to build custom image. we will use pre-defined mongo image from docker hub
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

